user_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('users.urls'), name='user_app')
]

# Adding media as a url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views
from .views import CustomPasswordResetView
from .views import (
    UserListView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    UserRegistrationView,
    UserProfile,
    InviteUserView,  
)
from .views import (
    CustomPasswordResetView, 
    CustomPasswordResetConfirmView, 
    CustomLogoutView, 
    UserRegistrationView, 
    UserListView, 
    UserCreateView, 
    UserUpdateView, 
    UserDeleteView, 
    UserProfile, 
    home, 
    InviteUserView
)
from django.contrib.auth.views import LoginView, LogoutView
from .views import UserRegistrationView 


app_name = 'user_app'
urlpatterns = [
    path('', views.home, name='home'),
        path('user/invite/', views.InviteUserView.as_view(template_name='users/invite.html'), name='invite'),
    path('user/list/a/', views.UserListView.as_view(), name='list'),
    path('user/create/a/', views.UserCreateView.as_view(), name='create'),
    path('user/update/<int:pk>/a/', views.UserUpdateView.as_view(), name='update'),
    path('user/delete/<int:pk>/a/', views.UserDeleteView.as_view(), name='delete'),
     path('user/register/c/', UserRegistrationView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('user/profile/<int:pk>/c/', views.UserProfile.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(next_page='user_app:home'), name='logout'),

        path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from users.models import MyUser, Profile


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email address',
            'type': 'email',
            'name': 'email',
            'autocomplete': 'email',
        })
    )

    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None):
        subject = render_to_string(subject_template_name, context)
        subject = ''.join(subject.splitlines())
        body = render_to_string(email_template_name, context)
        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name:
            html_email = render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')
        email_message.send()

    def save(self, domain_override=None,
             subject_template_name='users/password_reset_subject.txt',
             email_template_name='users/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None,
             extra_email_context=None):
        """
        Generate a one-use only link for resetting password and send it to the user.
        """
        email = self.cleaned_data["email"]
        email_field_name = MyUser.get_email_field_name()
        for user in self.get_users(email):
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            context = {
                'email': email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
                **(extra_email_context or {}),
            }
            self.send_mail(
                subject_template_name, email_template_name, context, from_email,
                user.email, html_email_template_name=html_email_template_name,
            )


class UserCreateForm(forms.ModelForm):
    """ User Create or Registration Form """
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'password', 'city')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UserUpdateForm(forms.ModelForm):
    """ User Update Form by Admin """
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'city', 'user_type')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'user_type': forms.Select(attrs={'class': 'form-control'}),
        }


class CustomerUpdateForm(forms.ModelForm):
    """ User Update Form for Customer """
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'city')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CustomerProfileForm(forms.ModelForm):
    """ User profile photo form """
    class Meta:
        model = Profile
        fields = ('image',)
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }


class InviteUserForm(forms.Form):
    email = forms.EmailField(label='Email')
    USER_TYPE_CHOICES = [
        ('admin', 'Admin'),
        ('customer', 'Customer'),
    ]
    user_type = forms.ChoiceField(choices=USER_TYPE_CHOICES, label='User Type')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.utils.safestring import mark_safe
from django.core.mail import send_mail
from django.contrib.auth.forms import SetPasswordForm  # Import this line

from users.models import MyUser
from users.forms import UserCreateForm, UserUpdateForm, CustomerUpdateForm, CustomerProfileForm, CustomPasswordResetForm, InviteUserForm
from django.contrib.auth.views import PasswordResetView, LogoutView, PasswordResetConfirmView
from rest_framework_simplejwt.tokens import AccessToken
from rest_framework_simplejwt.exceptions import TokenError
from .utils import generate_invite_token, decrypt_password
from rest_framework.exceptions import AuthenticationFailed
from rest_framework_simplejwt.tokens import UntypedToken
from datetime import datetime, timezone

class MyMixin(LoginRequiredMixin, UserPassesTestMixin):
    """Mixin for Authentication and User is Admin or not."""
    def test_func(self):
        return self.request.user.user_type == 'admin'

class InviteUserView(MyMixin, FormView):
    form_class = InviteUserForm
    template_name = 'users/invite.html'

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user_type = form.cleaned_data['user_type']
        
        # Generate token and registration link
        token = generate_invite_token(email, user_type)
        register_url = self.request.build_absolute_uri(reverse('user_app:register')) + f'?token={token}'
        
        # Send invitation email
        send_mail(
            'Invite to Register',
            f'Please register using the following link: {register_url}',
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
        )
        
        messages.success(self.request, f'Invitation sent to {email}.')
        return redirect(reverse('user_app:invite'))

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('user_app:password_reset_complete')
    form_class = SetPasswordForm

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, 'Your password has been changed successfully. Please log in.')
        return super().form_valid(form)

class CustomLogoutView(LogoutView):
    def get_next_page(self):
        return reverse_lazy('user_app:home')

class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_url = reverse_lazy('user_app:password_reset_done')
    template_name = 'users/password_reset.html'

@login_required
def home(request):
    """ Home Page """
    admin_count = MyUser.objects.filter(user_type='admin').count()
    customer_count = MyUser.objects.filter(user_type='customer').count()
    context = {
        'a_count': admin_count,
        'c_count': customer_count,
    }
    return render(request, 'users/home.html', context)



class UserRegistrationView(CreateView):
    model = MyUser
    form_class = UserCreateForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('user_app:home')

    def dispatch(self, request, *args, **kwargs):
        token = request.GET.get('token')
        self.email_from_token = None
        self.user_type = None

        if token:
            try:
                decoded_token = AccessToken(token)
                exp_timestamp = decoded_token.get("exp")

                # Convert the Unix timestamp to a datetime object
                exp_datetime = datetime.fromtimestamp(exp_timestamp, tz=timezone.utc)

                if datetime.now(timezone.utc) > exp_datetime:
                    raise TokenError("Token has expired.")
                self.email_from_token = decoded_token.get('email')
                self.user_type = decoded_token.get('user_type')
            except TokenError:
                messages.error(request, 'The registration link is invalid or has expired.')
                return redirect(reverse_lazy('user_app:invite'))
        else:
            messages.error(request, 'Invalid registration link.')
            return redirect(reverse_lazy('user_app:invite'))

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user_email = form.cleaned_data['email']

        if user_email != self.email_from_token:
            form.add_error('email', 'The email does not match the one used for invitation.')
            return self.form_invalid(form)

        user.set_password(form.cleaned_data['password'])
        user.user_type = self.user_type
        user.save()
        
        messages.success(self.request, f"{user.username} is created successfully!")
        return redirect(self.success_url)




class UserListView(MyMixin, ListView):
    model = MyUser
    template_name = 'users/list.html'
    context_object_name = 'data'

class UserCreateView(MyMixin, CreateView):
    model = MyUser
    form_class = UserCreateForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('user_app:list')

    def form_valid(self, form):
        user = form.save(commit=False)
        password = form.cleaned_data['password']
        user.set_password(password)
        messages.success(self.request, f"{user.username} is created successfully!")
        user.save()
        return redirect(reverse_lazy('user_app:list'))

class UserUpdateView(MyMixin, UpdateView):
    model = MyUser
    form_class = UserUpdateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('user_app:list')

    def form_valid(self, form):
        super().form_valid(form)
        messages.success(self.request, "User is updated successfully!")
        return redirect(reverse_lazy('user_app:list'))

class UserDeleteView(MyMixin, DeleteView):
    model = MyUser
    template_name = 'users/delete.html'
    success_url = reverse_lazy('user_app:list')

    def form_valid(self, form):
        super().form_valid(form)
        messages.warning(self.request, "User is deleted successfully!")
        return redirect(reverse_lazy('user_app:list'))

class UserProfile(LoginRequiredMixin, UpdateView):
    def get(self, request, **kwargs):
        user = request.user
        data = MyUser.objects.get(id=user.id)
        c_form = CustomerUpdateForm(instance=user)
        p_form = CustomerProfileForm(instance=user.profile)

        context = {
            'data': data,
            'c_form': c_form,
            'p_form': p_form,
        }
        return render(request, 'users/profile.html', context)

    def post(self, request, *args, **kwargs):
        user = request.user
        c_form = CustomerUpdateForm(request.POST, instance=user)
        p_form = CustomerProfileForm(request.POST, request.FILES, instance=user.profile)
        if c_form.is_valid() and p_form.is_valid():
            username = c_form.cleaned_data['username']
            c_form.save()
            p_form.save()
            messages.success(request, f"{username}'s profile has been updated successfully!")
        return redirect(reverse_lazy('user_app:profile', kwargs={'pk': user.id}))

def login_view(request):
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            encrypted_password = form.cleaned_data['password']
            username = form.cleaned_data['username']
            secret_key = 'your-secret-key'  # Use your actual secret key

            # Decrypt the password
            try:
                password = decrypt_password(encrypted_password, secret_key)
            except Exception as e:
                # Handle decryption errors
                return render(request, 'users/login.html', {'form': form, 'error': 'Invalid login credentials.'})

            # Authenticate the user
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')  # Redirect to the home page after login
            else:
                # Invalid credentials
                return render(request, 'users/login.html', {'form': form, 'error': 'Invalid login credentials.'})
    else:
        form = CustomLoginForm()
    return render(request, 'users/login.html', {'form': form})

templates/users/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-lg-5 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <h2 class="card-title">Delete User</h2>
                </div>
                <div class="row">
                    <p style="font-size:16px;">Are you sure, wants to delete user?</p>
                </div>
                <br>
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="text-center">
                                <a href="{% url 'user_app:list' %}" class="btn btn-primary mx-1">Cancel</a>
                                <input class="btn btn-danger" value="Delete" type="submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/users/invite_users.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Invite Users</h3>
                            <hr>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.username | as_crispy_field }}
                                </div>
                                <div class="form-group">
                                    {{ form.password | as_crispy_field }}
                                </div>
                                <hr>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-block enter-btn">Login</button>
                                </div>
                                <hr>
                                <p class="sign-up">Don't have an Account?<a href="{% url 'user_app:register' %}"> Sign Up</a></p>
                                <p class="forgot-password text-right">Forgot Password? <a href="{% url 'user_app:password_reset' %}">Forgot Password?</a></p>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>

templates/users/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-10">
          <h2 class="card-title">User's List</h2>
        </div>
        <div class="col-md-2">
          <a href="{% url 'user_app:create' %}" class="btn btn-primary">Add New User</a>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Username</th>
              <th>Email</th>
              <th>City</th>
              <th>User Type</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          {% for user in data %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ user.first_name }} {{ user.last_name }}</td>
              <td>{{ user.username }}</td>
              <td>{{ user.email }}</td>
              <td>{{ user.city }}</td>
              <td>{{ user.user_type }}</td>
              <td>
                <a href="{% url 'user_app:update' user.id %}" class="btn btn-primary mx-1">Edit</a>
                <a href="{% url 'user_app:delete' user.id %}" class="btn btn-danger mx-1">Delete</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/users/login.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Login</h3>
                            <hr>
                            <form id="login-form"  method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.username | as_crispy_field }}
                                </div>
                                <div class="form-group">
                                    {{ form.password | as_crispy_field }}
                                </div>
                                <hr>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-block enter-btn">Login</button>
                                </div>
                                <hr>
                                <!-- <p class="sign-up">Don't have an Account?<a href="{% url 'user_app:register' %}"> Sign Up</a></p> -->
                                <p class="forgot-password text-right">Forgot Password? <a href="{% url 'user_app:password_reset' %}">Forgot Password?</a></p>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"></script>

    
    <!-- <script>
        document.getElementById('login-form').addEventListener('submit', function(event) {
            var form = event.target;
            var passwordField = form.querySelector('input[name="password"]');
            var password = passwordField.value;
    
            // Encrypt the password
            var secretKey = 'your-secret-key';  // Use your actual secret key
            var encryptedPassword = CryptoJS.AES.encrypt(password, secretKey).toString();
            console.log(`Encrypted password: ${encryptedPassword}`);  // Log the encrypted password for debugging
    
            // Set the encrypted password
            passwordField.value = encryptedPassword;
        });
    </script> -->

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>

templates/users/password_reset.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Reset my password</h3>
                            <hr>
                            <form method="post" action="{% url 'user_app:password_reset' %}">
                                {% csrf_token %}
                                {{ form.as_p }}
                           
                           
                                <hr>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-block enter-btn">Reset my password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>

templates/users/password_reset_complete.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Password Reset Complete</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Password Reset Complete</h3>

                            <p>Your password has been set. You can now <a href="{% url 'user_app:login' %}">log in</a> with your new password.</p>
                                
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>